# Generated by Django 5.0.3 on 2024-03-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="createdAt",
            new_name="created_at",
        ),
    ]
